### ISSUE TITLE
Front end filter to show 2019 members only

### ISSUE THREAD

**Issue by emilyfeder** [jcua-tech/jcua-renxt#32]
Apparently, the Constituent Code: Member, that we've been using, describes anyone who's ever been a member, and using the Attribute: 2019 Member, would get everyone who is currently a member. JCUA liked the idea of having a specific filter on the ui that would pare the list down to just 2019 members. Obviously that means we would need to pull that attribute into the member data requested by the UI.

**Comment by emrapport** [comment]
I updated so that we will pull in 2019 member data, but still need to figure out how to make that resilient to future years' data (waiting for response from JCUA folks). Noah started on the front end filtering for this.

**Comment by Noleli** [comment]
Closed by #44.
