### ISSUE TITLE
Geocode + display members' Home Addresses

### ISSUE THREAD

**Issue by emilyfeder** [jcua-tech/jcua-renxt#34]
Each constituent's preferred address is actually their 'Mailing Address' which can be a business address, which obviously is not helpful for determining ward number. It seems that the endpoint we use to get the constituent list only gives the preferred address. 2 options: Hannah offered to go through the data and create a field called 'Mailing Address' and ensure that everyone's 'Preferred Address' refers to their 'Home Address'. Or we could ask a separate endpoint for the 'Home Addresses' for each constituent.

**Comment by emrapport** [comment]
Since there are so many discrepancies in folks primary/home addresses, we think that the best move is to continue using primary addresses and show an indicator if the address isn't a home address so that JCUA can review and re-code if need be. Emily made this fix (reviewed by Noah) on 3/30.
